import type { EditPlan } from "./schema";

export const defaultPlan: EditPlan = {
  version: "1.0",
  profile: "tech-story-v1",
  source_filename: "source.mp4",
  source_url: "source.mp4",
  source_metadata: {
    width: 720,
    height: 1280,
    fps: 30,
    frame_count: 90,
    duration_seconds: 3,
  },
  output: { width: 1080, height: 1920, fps: 30 },
  duration_ms: 3000,
  style_variant: "tech-news",
  timeline: [
    {
      source_start_ms: 0,
      source_end_ms: 3000,
      output_start_ms: 0,
      output_end_ms: 3000,
    },
  ],
  caption_pages: [],
  scenes: [
    {
      id: "scene-1",
      start_ms: 0,
      end_ms: 3000,
      role: "hook",
      layout: "presenter",
      zoom: 1,
      visual_id: null,
      treatment: null,
      asset_id: null,
      motion: "live-footage",
    },
  ],
  reframing: [{ time_ms: 0, x: 0.5, y: 0.42, scale: 1.12 }],
  graphics: [],
  editorial_visuals: [],
  assets: [],
  audio: {
    integrated_lufs: -14.2,
    true_peak_dbtp: -1,
    music_bpm: 120,
    dialogue_asset_id: null,
    dialogue_offset_ms: 0,
    music_asset_id: null,
    music_duck_db: 6,
    music_base_gain_db: -18,
    music_gain_automation: [],
    speech_protection_windows: [],
    sfx_asset_ids: [],
    sfx_cues: [],
  },
  qc_targets: {
    integrated_lufs: -14.2,
    loudness_tolerance: 0.5,
    true_peak_dbtp: -1,
    max_silence_ms: 120,
    max_black_frame_ratio: 0.001,
    max_freeze_frame_ratio: 0.14,
    min_cuts_per_minute: 30,
    max_cuts_per_minute: 75,
    min_median_shot_ms: 800,
    max_median_shot_ms: 1800,
    min_cut_onset_percent: 70,
    min_meaningful_visual_coverage: 0.55,
    min_style_score: 80,
  },
};
